/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as ApiExtractProductsRouteImport } from './routes/api/extract-products'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AppVendedorRouteImport } from './routes/_app.vendedor'
import { Route as AppSobreRouteImport } from './routes/_app.sobre'
import { Route as AppLojasRouteImport } from './routes/_app.lojas'
import { Route as AppFavoritosRouteImport } from './routes/_app.favoritos'
import { Route as AppContaRouteImport } from './routes/_app.conta'
import { Route as AppCheckoutRouteImport } from './routes/_app.checkout'
import { Route as AppCategoriasRouteImport } from './routes/_app.categorias'
import { Route as AppCarrinhoRouteImport } from './routes/_app.carrinho'
import { Route as AppBlogRouteImport } from './routes/_app.blog'
import { Route as AppAssistenteRouteImport } from './routes/_app.assistente'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppAdminIndexRouteImport } from './routes/_app.admin.index'
import { Route as AppVendedorImportarRouteImport } from './routes/_app.vendedor.importar'
import { Route as AppRastreioOrderIdRouteImport } from './routes/_app.rastreio.$orderId'
import { Route as AppProdutoSlugRouteImport } from './routes/_app.produto.$slug'
import { Route as AppAdminExtratoRouteImport } from './routes/_app.admin.extrato'
import { Route as AppVendedorImportarProcessandoRouteImport } from './routes/_app.vendedor.importar.processando'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiExtractProductsRoute = ApiExtractProductsRouteImport.update({
  id: '/api/extract-products',
  path: '/api/extract-products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVendedorRoute = AppVendedorRouteImport.update({
  id: '/vendedor',
  path: '/vendedor',
  getParentRoute: () => AppRoute,
} as any)
const AppSobreRoute = AppSobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => AppRoute,
} as any)
const AppLojasRoute = AppLojasRouteImport.update({
  id: '/lojas',
  path: '/lojas',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritosRoute = AppFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => AppRoute,
} as any)
const AppContaRoute = AppContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckoutRoute = AppCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriasRoute = AppCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AppRoute,
} as any)
const AppCarrinhoRoute = AppCarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => AppRoute,
} as any)
const AppBlogRoute = AppBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistenteRoute = AppAssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppVendedorImportarRoute = AppVendedorImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => AppVendedorRoute,
} as any)
const AppRastreioOrderIdRoute = AppRastreioOrderIdRouteImport.update({
  id: '/rastreio/$orderId',
  path: '/rastreio/$orderId',
  getParentRoute: () => AppRoute,
} as any)
const AppProdutoSlugRoute = AppProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminExtratoRoute = AppAdminExtratoRouteImport.update({
  id: '/extrato',
  path: '/extrato',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppVendedorImportarProcessandoRoute =
  AppVendedorImportarProcessandoRouteImport.update({
    id: '/processando',
    path: '/processando',
    getParentRoute: () => AppVendedorImportarRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/assistente': typeof AppAssistenteRoute
  '/blog': typeof AppBlogRoute
  '/carrinho': typeof AppCarrinhoRoute
  '/categorias': typeof AppCategoriasRoute
  '/checkout': typeof AppCheckoutRoute
  '/conta': typeof AppContaRoute
  '/favoritos': typeof AppFavoritosRoute
  '/lojas': typeof AppLojasRoute
  '/sobre': typeof AppSobreRoute
  '/vendedor': typeof AppVendedorRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/extract-products': typeof ApiExtractProductsRoute
  '/admin/extrato': typeof AppAdminExtratoRoute
  '/produto/$slug': typeof AppProdutoSlugRoute
  '/rastreio/$orderId': typeof AppRastreioOrderIdRoute
  '/vendedor/importar': typeof AppVendedorImportarRouteWithChildren
  '/admin/': typeof AppAdminIndexRoute
  '/vendedor/importar/processando': typeof AppVendedorImportarProcessandoRoute
}
export interface FileRoutesByTo {
  '/assistente': typeof AppAssistenteRoute
  '/blog': typeof AppBlogRoute
  '/carrinho': typeof AppCarrinhoRoute
  '/categorias': typeof AppCategoriasRoute
  '/checkout': typeof AppCheckoutRoute
  '/conta': typeof AppContaRoute
  '/favoritos': typeof AppFavoritosRoute
  '/lojas': typeof AppLojasRoute
  '/sobre': typeof AppSobreRoute
  '/vendedor': typeof AppVendedorRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/extract-products': typeof ApiExtractProductsRoute
  '/': typeof AppIndexRoute
  '/admin/extrato': typeof AppAdminExtratoRoute
  '/produto/$slug': typeof AppProdutoSlugRoute
  '/rastreio/$orderId': typeof AppRastreioOrderIdRoute
  '/vendedor/importar': typeof AppVendedorImportarRouteWithChildren
  '/admin': typeof AppAdminIndexRoute
  '/vendedor/importar/processando': typeof AppVendedorImportarProcessandoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/assistente': typeof AppAssistenteRoute
  '/_app/blog': typeof AppBlogRoute
  '/_app/carrinho': typeof AppCarrinhoRoute
  '/_app/categorias': typeof AppCategoriasRoute
  '/_app/checkout': typeof AppCheckoutRoute
  '/_app/conta': typeof AppContaRoute
  '/_app/favoritos': typeof AppFavoritosRoute
  '/_app/lojas': typeof AppLojasRoute
  '/_app/sobre': typeof AppSobreRoute
  '/_app/vendedor': typeof AppVendedorRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/extract-products': typeof ApiExtractProductsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/extrato': typeof AppAdminExtratoRoute
  '/_app/produto/$slug': typeof AppProdutoSlugRoute
  '/_app/rastreio/$orderId': typeof AppRastreioOrderIdRoute
  '/_app/vendedor/importar': typeof AppVendedorImportarRouteWithChildren
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/vendedor/importar/processando': typeof AppVendedorImportarProcessandoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assistente'
    | '/blog'
    | '/carrinho'
    | '/categorias'
    | '/checkout'
    | '/conta'
    | '/favoritos'
    | '/lojas'
    | '/sobre'
    | '/vendedor'
    | '/api/chat'
    | '/api/extract-products'
    | '/admin/extrato'
    | '/produto/$slug'
    | '/rastreio/$orderId'
    | '/vendedor/importar'
    | '/admin/'
    | '/vendedor/importar/processando'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/assistente'
    | '/blog'
    | '/carrinho'
    | '/categorias'
    | '/checkout'
    | '/conta'
    | '/favoritos'
    | '/lojas'
    | '/sobre'
    | '/vendedor'
    | '/api/chat'
    | '/api/extract-products'
    | '/'
    | '/admin/extrato'
    | '/produto/$slug'
    | '/rastreio/$orderId'
    | '/vendedor/importar'
    | '/admin'
    | '/vendedor/importar/processando'
  id:
    | '__root__'
    | '/_app'
    | '/_app/admin'
    | '/_app/assistente'
    | '/_app/blog'
    | '/_app/carrinho'
    | '/_app/categorias'
    | '/_app/checkout'
    | '/_app/conta'
    | '/_app/favoritos'
    | '/_app/lojas'
    | '/_app/sobre'
    | '/_app/vendedor'
    | '/api/chat'
    | '/api/extract-products'
    | '/_app/'
    | '/_app/admin/extrato'
    | '/_app/produto/$slug'
    | '/_app/rastreio/$orderId'
    | '/_app/vendedor/importar'
    | '/_app/admin/'
    | '/_app/vendedor/importar/processando'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiExtractProductsRoute: typeof ApiExtractProductsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/extract-products': {
      id: '/api/extract-products'
      path: '/api/extract-products'
      fullPath: '/api/extract-products'
      preLoaderRoute: typeof ApiExtractProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vendedor': {
      id: '/_app/vendedor'
      path: '/vendedor'
      fullPath: '/vendedor'
      preLoaderRoute: typeof AppVendedorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sobre': {
      id: '/_app/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof AppSobreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lojas': {
      id: '/_app/lojas'
      path: '/lojas'
      fullPath: '/lojas'
      preLoaderRoute: typeof AppLojasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/favoritos': {
      id: '/_app/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof AppFavoritosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/conta': {
      id: '/_app/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof AppContaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/checkout': {
      id: '/_app/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AppCheckoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categorias': {
      id: '/_app/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AppCategoriasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/carrinho': {
      id: '/_app/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof AppCarrinhoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/blog': {
      id: '/_app/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof AppBlogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assistente': {
      id: '/_app/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AppAssistenteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/vendedor/importar': {
      id: '/_app/vendedor/importar'
      path: '/importar'
      fullPath: '/vendedor/importar'
      preLoaderRoute: typeof AppVendedorImportarRouteImport
      parentRoute: typeof AppVendedorRoute
    }
    '/_app/rastreio/$orderId': {
      id: '/_app/rastreio/$orderId'
      path: '/rastreio/$orderId'
      fullPath: '/rastreio/$orderId'
      preLoaderRoute: typeof AppRastreioOrderIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/produto/$slug': {
      id: '/_app/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof AppProdutoSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/extrato': {
      id: '/_app/admin/extrato'
      path: '/extrato'
      fullPath: '/admin/extrato'
      preLoaderRoute: typeof AppAdminExtratoRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/vendedor/importar/processando': {
      id: '/_app/vendedor/importar/processando'
      path: '/processando'
      fullPath: '/vendedor/importar/processando'
      preLoaderRoute: typeof AppVendedorImportarProcessandoRouteImport
      parentRoute: typeof AppVendedorImportarRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminExtratoRoute: typeof AppAdminExtratoRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminExtratoRoute: AppAdminExtratoRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppVendedorImportarRouteChildren {
  AppVendedorImportarProcessandoRoute: typeof AppVendedorImportarProcessandoRoute
}

const AppVendedorImportarRouteChildren: AppVendedorImportarRouteChildren = {
  AppVendedorImportarProcessandoRoute: AppVendedorImportarProcessandoRoute,
}

const AppVendedorImportarRouteWithChildren =
  AppVendedorImportarRoute._addFileChildren(AppVendedorImportarRouteChildren)

interface AppVendedorRouteChildren {
  AppVendedorImportarRoute: typeof AppVendedorImportarRouteWithChildren
}

const AppVendedorRouteChildren: AppVendedorRouteChildren = {
  AppVendedorImportarRoute: AppVendedorImportarRouteWithChildren,
}

const AppVendedorRouteWithChildren = AppVendedorRoute._addFileChildren(
  AppVendedorRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppAssistenteRoute: typeof AppAssistenteRoute
  AppBlogRoute: typeof AppBlogRoute
  AppCarrinhoRoute: typeof AppCarrinhoRoute
  AppCategoriasRoute: typeof AppCategoriasRoute
  AppCheckoutRoute: typeof AppCheckoutRoute
  AppContaRoute: typeof AppContaRoute
  AppFavoritosRoute: typeof AppFavoritosRoute
  AppLojasRoute: typeof AppLojasRoute
  AppSobreRoute: typeof AppSobreRoute
  AppVendedorRoute: typeof AppVendedorRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppProdutoSlugRoute: typeof AppProdutoSlugRoute
  AppRastreioOrderIdRoute: typeof AppRastreioOrderIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppAssistenteRoute: AppAssistenteRoute,
  AppBlogRoute: AppBlogRoute,
  AppCarrinhoRoute: AppCarrinhoRoute,
  AppCategoriasRoute: AppCategoriasRoute,
  AppCheckoutRoute: AppCheckoutRoute,
  AppContaRoute: AppContaRoute,
  AppFavoritosRoute: AppFavoritosRoute,
  AppLojasRoute: AppLojasRoute,
  AppSobreRoute: AppSobreRoute,
  AppVendedorRoute: AppVendedorRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppProdutoSlugRoute: AppProdutoSlugRoute,
  AppRastreioOrderIdRoute: AppRastreioOrderIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiExtractProductsRoute: ApiExtractProductsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
