/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as ApiExtractProductsRouteImport } from './routes/api/extract-products'
import { Route as ApiExtractFromUrlRouteImport } from './routes/api/extract-from-url'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AppVendedorRouteImport } from './routes/_app.vendedor'
import { Route as AppSobreRouteImport } from './routes/_app.sobre'
import { Route as AppSertaoRouteImport } from './routes/_app.sertao'
import { Route as AppLojasRouteImport } from './routes/_app.lojas'
import { Route as AppLicuriRouteImport } from './routes/_app.licuri'
import { Route as AppLaboratorioRouteImport } from './routes/_app.laboratorio'
import { Route as AppImpactoRouteImport } from './routes/_app.impacto'
import { Route as AppIaraRouteImport } from './routes/_app.iara'
import { Route as AppFavoritosRouteImport } from './routes/_app.favoritos'
import { Route as AppEmpresasRouteImport } from './routes/_app.empresas'
import { Route as AppCuradoriaRouteImport } from './routes/_app.curadoria'
import { Route as AppContaRouteImport } from './routes/_app.conta'
import { Route as AppClubeDoLicuriRouteImport } from './routes/_app.clube-do-licuri'
import { Route as AppCheckoutRouteImport } from './routes/_app.checkout'
import { Route as AppCategoriasRouteImport } from './routes/_app.categorias'
import { Route as AppCasaDoLicuriRouteImport } from './routes/_app.casa-do-licuri'
import { Route as AppCarrinhoRouteImport } from './routes/_app.carrinho'
import { Route as AppBlogRouteImport } from './routes/_app.blog'
import { Route as AppAssistenteRouteImport } from './routes/_app.assistente'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppAcademiaRouteImport } from './routes/_app.academia'
import { Route as AppAdminIndexRouteImport } from './routes/_app.admin.index'
import { Route as AppVendedorLoginRouteImport } from './routes/_app.vendedor.login'
import { Route as AppVendedorImportarRouteImport } from './routes/_app.vendedor.importar'
import { Route as AppRastreioOrderIdRouteImport } from './routes/_app.rastreio.$orderId'
import { Route as AppProdutoSlugRouteImport } from './routes/_app.produto.$slug'
import { Route as AppPedidoOrderIdRouteImport } from './routes/_app.pedido.$orderId'
import { Route as AppLojaIdRouteImport } from './routes/_app.loja.$id'
import { Route as AppAdminExtratoRouteImport } from './routes/_app.admin.extrato'
import { Route as AppVendedorImportarProcessandoRouteImport } from './routes/_app.vendedor.importar.processando'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiExtractProductsRoute = ApiExtractProductsRouteImport.update({
  id: '/api/extract-products',
  path: '/api/extract-products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtractFromUrlRoute = ApiExtractFromUrlRouteImport.update({
  id: '/api/extract-from-url',
  path: '/api/extract-from-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVendedorRoute = AppVendedorRouteImport.update({
  id: '/vendedor',
  path: '/vendedor',
  getParentRoute: () => AppRoute,
} as any)
const AppSobreRoute = AppSobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => AppRoute,
} as any)
const AppSertaoRoute = AppSertaoRouteImport.update({
  id: '/sertao',
  path: '/sertao',
  getParentRoute: () => AppRoute,
} as any)
const AppLojasRoute = AppLojasRouteImport.update({
  id: '/lojas',
  path: '/lojas',
  getParentRoute: () => AppRoute,
} as any)
const AppLicuriRoute = AppLicuriRouteImport.update({
  id: '/licuri',
  path: '/licuri',
  getParentRoute: () => AppRoute,
} as any)
const AppLaboratorioRoute = AppLaboratorioRouteImport.update({
  id: '/laboratorio',
  path: '/laboratorio',
  getParentRoute: () => AppRoute,
} as any)
const AppImpactoRoute = AppImpactoRouteImport.update({
  id: '/impacto',
  path: '/impacto',
  getParentRoute: () => AppRoute,
} as any)
const AppIaraRoute = AppIaraRouteImport.update({
  id: '/iara',
  path: '/iara',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritosRoute = AppFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpresasRoute = AppEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AppRoute,
} as any)
const AppCuradoriaRoute = AppCuradoriaRouteImport.update({
  id: '/curadoria',
  path: '/curadoria',
  getParentRoute: () => AppRoute,
} as any)
const AppContaRoute = AppContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AppRoute,
} as any)
const AppClubeDoLicuriRoute = AppClubeDoLicuriRouteImport.update({
  id: '/clube-do-licuri',
  path: '/clube-do-licuri',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckoutRoute = AppCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriasRoute = AppCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AppRoute,
} as any)
const AppCasaDoLicuriRoute = AppCasaDoLicuriRouteImport.update({
  id: '/casa-do-licuri',
  path: '/casa-do-licuri',
  getParentRoute: () => AppRoute,
} as any)
const AppCarrinhoRoute = AppCarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => AppRoute,
} as any)
const AppBlogRoute = AppBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistenteRoute = AppAssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademiaRoute = AppAcademiaRouteImport.update({
  id: '/academia',
  path: '/academia',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppVendedorLoginRoute = AppVendedorLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppVendedorRoute,
} as any)
const AppVendedorImportarRoute = AppVendedorImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => AppVendedorRoute,
} as any)
const AppRastreioOrderIdRoute = AppRastreioOrderIdRouteImport.update({
  id: '/rastreio/$orderId',
  path: '/rastreio/$orderId',
  getParentRoute: () => AppRoute,
} as any)
const AppProdutoSlugRoute = AppProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppPedidoOrderIdRoute = AppPedidoOrderIdRouteImport.update({
  id: '/pedido/$orderId',
  path: '/pedido/$orderId',
  getParentRoute: () => AppRoute,
} as any)
const AppLojaIdRoute = AppLojaIdRouteImport.update({
  id: '/loja/$id',
  path: '/loja/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminExtratoRoute = AppAdminExtratoRouteImport.update({
  id: '/extrato',
  path: '/extrato',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppVendedorImportarProcessandoRoute =
  AppVendedorImportarProcessandoRouteImport.update({
    id: '/processando',
    path: '/processando',
    getParentRoute: () => AppVendedorImportarRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/academia': typeof AppAcademiaRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/assistente': typeof AppAssistenteRoute
  '/blog': typeof AppBlogRoute
  '/carrinho': typeof AppCarrinhoRoute
  '/casa-do-licuri': typeof AppCasaDoLicuriRoute
  '/categorias': typeof AppCategoriasRoute
  '/checkout': typeof AppCheckoutRoute
  '/clube-do-licuri': typeof AppClubeDoLicuriRoute
  '/conta': typeof AppContaRoute
  '/curadoria': typeof AppCuradoriaRoute
  '/empresas': typeof AppEmpresasRoute
  '/favoritos': typeof AppFavoritosRoute
  '/iara': typeof AppIaraRoute
  '/impacto': typeof AppImpactoRoute
  '/laboratorio': typeof AppLaboratorioRoute
  '/licuri': typeof AppLicuriRoute
  '/lojas': typeof AppLojasRoute
  '/sertao': typeof AppSertaoRoute
  '/sobre': typeof AppSobreRoute
  '/vendedor': typeof AppVendedorRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/extract-from-url': typeof ApiExtractFromUrlRoute
  '/api/extract-products': typeof ApiExtractProductsRoute
  '/admin/extrato': typeof AppAdminExtratoRoute
  '/loja/$id': typeof AppLojaIdRoute
  '/pedido/$orderId': typeof AppPedidoOrderIdRoute
  '/produto/$slug': typeof AppProdutoSlugRoute
  '/rastreio/$orderId': typeof AppRastreioOrderIdRoute
  '/vendedor/importar': typeof AppVendedorImportarRouteWithChildren
  '/vendedor/login': typeof AppVendedorLoginRoute
  '/admin/': typeof AppAdminIndexRoute
  '/vendedor/importar/processando': typeof AppVendedorImportarProcessandoRoute
}
export interface FileRoutesByTo {
  '/academia': typeof AppAcademiaRoute
  '/assistente': typeof AppAssistenteRoute
  '/blog': typeof AppBlogRoute
  '/carrinho': typeof AppCarrinhoRoute
  '/casa-do-licuri': typeof AppCasaDoLicuriRoute
  '/categorias': typeof AppCategoriasRoute
  '/checkout': typeof AppCheckoutRoute
  '/clube-do-licuri': typeof AppClubeDoLicuriRoute
  '/conta': typeof AppContaRoute
  '/curadoria': typeof AppCuradoriaRoute
  '/empresas': typeof AppEmpresasRoute
  '/favoritos': typeof AppFavoritosRoute
  '/iara': typeof AppIaraRoute
  '/impacto': typeof AppImpactoRoute
  '/laboratorio': typeof AppLaboratorioRoute
  '/licuri': typeof AppLicuriRoute
  '/lojas': typeof AppLojasRoute
  '/sertao': typeof AppSertaoRoute
  '/sobre': typeof AppSobreRoute
  '/vendedor': typeof AppVendedorRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/extract-from-url': typeof ApiExtractFromUrlRoute
  '/api/extract-products': typeof ApiExtractProductsRoute
  '/': typeof AppIndexRoute
  '/admin/extrato': typeof AppAdminExtratoRoute
  '/loja/$id': typeof AppLojaIdRoute
  '/pedido/$orderId': typeof AppPedidoOrderIdRoute
  '/produto/$slug': typeof AppProdutoSlugRoute
  '/rastreio/$orderId': typeof AppRastreioOrderIdRoute
  '/vendedor/importar': typeof AppVendedorImportarRouteWithChildren
  '/vendedor/login': typeof AppVendedorLoginRoute
  '/admin': typeof AppAdminIndexRoute
  '/vendedor/importar/processando': typeof AppVendedorImportarProcessandoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/academia': typeof AppAcademiaRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/assistente': typeof AppAssistenteRoute
  '/_app/blog': typeof AppBlogRoute
  '/_app/carrinho': typeof AppCarrinhoRoute
  '/_app/casa-do-licuri': typeof AppCasaDoLicuriRoute
  '/_app/categorias': typeof AppCategoriasRoute
  '/_app/checkout': typeof AppCheckoutRoute
  '/_app/clube-do-licuri': typeof AppClubeDoLicuriRoute
  '/_app/conta': typeof AppContaRoute
  '/_app/curadoria': typeof AppCuradoriaRoute
  '/_app/empresas': typeof AppEmpresasRoute
  '/_app/favoritos': typeof AppFavoritosRoute
  '/_app/iara': typeof AppIaraRoute
  '/_app/impacto': typeof AppImpactoRoute
  '/_app/laboratorio': typeof AppLaboratorioRoute
  '/_app/licuri': typeof AppLicuriRoute
  '/_app/lojas': typeof AppLojasRoute
  '/_app/sertao': typeof AppSertaoRoute
  '/_app/sobre': typeof AppSobreRoute
  '/_app/vendedor': typeof AppVendedorRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/extract-from-url': typeof ApiExtractFromUrlRoute
  '/api/extract-products': typeof ApiExtractProductsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/extrato': typeof AppAdminExtratoRoute
  '/_app/loja/$id': typeof AppLojaIdRoute
  '/_app/pedido/$orderId': typeof AppPedidoOrderIdRoute
  '/_app/produto/$slug': typeof AppProdutoSlugRoute
  '/_app/rastreio/$orderId': typeof AppRastreioOrderIdRoute
  '/_app/vendedor/importar': typeof AppVendedorImportarRouteWithChildren
  '/_app/vendedor/login': typeof AppVendedorLoginRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/vendedor/importar/processando': typeof AppVendedorImportarProcessandoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academia'
    | '/admin'
    | '/assistente'
    | '/blog'
    | '/carrinho'
    | '/casa-do-licuri'
    | '/categorias'
    | '/checkout'
    | '/clube-do-licuri'
    | '/conta'
    | '/curadoria'
    | '/empresas'
    | '/favoritos'
    | '/iara'
    | '/impacto'
    | '/laboratorio'
    | '/licuri'
    | '/lojas'
    | '/sertao'
    | '/sobre'
    | '/vendedor'
    | '/api/chat'
    | '/api/extract-from-url'
    | '/api/extract-products'
    | '/admin/extrato'
    | '/loja/$id'
    | '/pedido/$orderId'
    | '/produto/$slug'
    | '/rastreio/$orderId'
    | '/vendedor/importar'
    | '/vendedor/login'
    | '/admin/'
    | '/vendedor/importar/processando'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/academia'
    | '/assistente'
    | '/blog'
    | '/carrinho'
    | '/casa-do-licuri'
    | '/categorias'
    | '/checkout'
    | '/clube-do-licuri'
    | '/conta'
    | '/curadoria'
    | '/empresas'
    | '/favoritos'
    | '/iara'
    | '/impacto'
    | '/laboratorio'
    | '/licuri'
    | '/lojas'
    | '/sertao'
    | '/sobre'
    | '/vendedor'
    | '/api/chat'
    | '/api/extract-from-url'
    | '/api/extract-products'
    | '/'
    | '/admin/extrato'
    | '/loja/$id'
    | '/pedido/$orderId'
    | '/produto/$slug'
    | '/rastreio/$orderId'
    | '/vendedor/importar'
    | '/vendedor/login'
    | '/admin'
    | '/vendedor/importar/processando'
  id:
    | '__root__'
    | '/_app'
    | '/_app/academia'
    | '/_app/admin'
    | '/_app/assistente'
    | '/_app/blog'
    | '/_app/carrinho'
    | '/_app/casa-do-licuri'
    | '/_app/categorias'
    | '/_app/checkout'
    | '/_app/clube-do-licuri'
    | '/_app/conta'
    | '/_app/curadoria'
    | '/_app/empresas'
    | '/_app/favoritos'
    | '/_app/iara'
    | '/_app/impacto'
    | '/_app/laboratorio'
    | '/_app/licuri'
    | '/_app/lojas'
    | '/_app/sertao'
    | '/_app/sobre'
    | '/_app/vendedor'
    | '/api/chat'
    | '/api/extract-from-url'
    | '/api/extract-products'
    | '/_app/'
    | '/_app/admin/extrato'
    | '/_app/loja/$id'
    | '/_app/pedido/$orderId'
    | '/_app/produto/$slug'
    | '/_app/rastreio/$orderId'
    | '/_app/vendedor/importar'
    | '/_app/vendedor/login'
    | '/_app/admin/'
    | '/_app/vendedor/importar/processando'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiExtractFromUrlRoute: typeof ApiExtractFromUrlRoute
  ApiExtractProductsRoute: typeof ApiExtractProductsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/extract-products': {
      id: '/api/extract-products'
      path: '/api/extract-products'
      fullPath: '/api/extract-products'
      preLoaderRoute: typeof ApiExtractProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extract-from-url': {
      id: '/api/extract-from-url'
      path: '/api/extract-from-url'
      fullPath: '/api/extract-from-url'
      preLoaderRoute: typeof ApiExtractFromUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vendedor': {
      id: '/_app/vendedor'
      path: '/vendedor'
      fullPath: '/vendedor'
      preLoaderRoute: typeof AppVendedorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sobre': {
      id: '/_app/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof AppSobreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sertao': {
      id: '/_app/sertao'
      path: '/sertao'
      fullPath: '/sertao'
      preLoaderRoute: typeof AppSertaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lojas': {
      id: '/_app/lojas'
      path: '/lojas'
      fullPath: '/lojas'
      preLoaderRoute: typeof AppLojasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/licuri': {
      id: '/_app/licuri'
      path: '/licuri'
      fullPath: '/licuri'
      preLoaderRoute: typeof AppLicuriRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/laboratorio': {
      id: '/_app/laboratorio'
      path: '/laboratorio'
      fullPath: '/laboratorio'
      preLoaderRoute: typeof AppLaboratorioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/impacto': {
      id: '/_app/impacto'
      path: '/impacto'
      fullPath: '/impacto'
      preLoaderRoute: typeof AppImpactoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/iara': {
      id: '/_app/iara'
      path: '/iara'
      fullPath: '/iara'
      preLoaderRoute: typeof AppIaraRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/favoritos': {
      id: '/_app/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof AppFavoritosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/empresas': {
      id: '/_app/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof AppEmpresasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/curadoria': {
      id: '/_app/curadoria'
      path: '/curadoria'
      fullPath: '/curadoria'
      preLoaderRoute: typeof AppCuradoriaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/conta': {
      id: '/_app/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof AppContaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clube-do-licuri': {
      id: '/_app/clube-do-licuri'
      path: '/clube-do-licuri'
      fullPath: '/clube-do-licuri'
      preLoaderRoute: typeof AppClubeDoLicuriRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/checkout': {
      id: '/_app/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AppCheckoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categorias': {
      id: '/_app/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AppCategoriasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/casa-do-licuri': {
      id: '/_app/casa-do-licuri'
      path: '/casa-do-licuri'
      fullPath: '/casa-do-licuri'
      preLoaderRoute: typeof AppCasaDoLicuriRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/carrinho': {
      id: '/_app/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof AppCarrinhoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/blog': {
      id: '/_app/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof AppBlogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assistente': {
      id: '/_app/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AppAssistenteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/academia': {
      id: '/_app/academia'
      path: '/academia'
      fullPath: '/academia'
      preLoaderRoute: typeof AppAcademiaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/vendedor/login': {
      id: '/_app/vendedor/login'
      path: '/login'
      fullPath: '/vendedor/login'
      preLoaderRoute: typeof AppVendedorLoginRouteImport
      parentRoute: typeof AppVendedorRoute
    }
    '/_app/vendedor/importar': {
      id: '/_app/vendedor/importar'
      path: '/importar'
      fullPath: '/vendedor/importar'
      preLoaderRoute: typeof AppVendedorImportarRouteImport
      parentRoute: typeof AppVendedorRoute
    }
    '/_app/rastreio/$orderId': {
      id: '/_app/rastreio/$orderId'
      path: '/rastreio/$orderId'
      fullPath: '/rastreio/$orderId'
      preLoaderRoute: typeof AppRastreioOrderIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/produto/$slug': {
      id: '/_app/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof AppProdutoSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pedido/$orderId': {
      id: '/_app/pedido/$orderId'
      path: '/pedido/$orderId'
      fullPath: '/pedido/$orderId'
      preLoaderRoute: typeof AppPedidoOrderIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loja/$id': {
      id: '/_app/loja/$id'
      path: '/loja/$id'
      fullPath: '/loja/$id'
      preLoaderRoute: typeof AppLojaIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/extrato': {
      id: '/_app/admin/extrato'
      path: '/extrato'
      fullPath: '/admin/extrato'
      preLoaderRoute: typeof AppAdminExtratoRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/vendedor/importar/processando': {
      id: '/_app/vendedor/importar/processando'
      path: '/processando'
      fullPath: '/vendedor/importar/processando'
      preLoaderRoute: typeof AppVendedorImportarProcessandoRouteImport
      parentRoute: typeof AppVendedorImportarRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminExtratoRoute: typeof AppAdminExtratoRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminExtratoRoute: AppAdminExtratoRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppVendedorImportarRouteChildren {
  AppVendedorImportarProcessandoRoute: typeof AppVendedorImportarProcessandoRoute
}

const AppVendedorImportarRouteChildren: AppVendedorImportarRouteChildren = {
  AppVendedorImportarProcessandoRoute: AppVendedorImportarProcessandoRoute,
}

const AppVendedorImportarRouteWithChildren =
  AppVendedorImportarRoute._addFileChildren(AppVendedorImportarRouteChildren)

interface AppVendedorRouteChildren {
  AppVendedorImportarRoute: typeof AppVendedorImportarRouteWithChildren
  AppVendedorLoginRoute: typeof AppVendedorLoginRoute
}

const AppVendedorRouteChildren: AppVendedorRouteChildren = {
  AppVendedorImportarRoute: AppVendedorImportarRouteWithChildren,
  AppVendedorLoginRoute: AppVendedorLoginRoute,
}

const AppVendedorRouteWithChildren = AppVendedorRoute._addFileChildren(
  AppVendedorRouteChildren,
)

interface AppRouteChildren {
  AppAcademiaRoute: typeof AppAcademiaRoute
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppAssistenteRoute: typeof AppAssistenteRoute
  AppBlogRoute: typeof AppBlogRoute
  AppCarrinhoRoute: typeof AppCarrinhoRoute
  AppCasaDoLicuriRoute: typeof AppCasaDoLicuriRoute
  AppCategoriasRoute: typeof AppCategoriasRoute
  AppCheckoutRoute: typeof AppCheckoutRoute
  AppClubeDoLicuriRoute: typeof AppClubeDoLicuriRoute
  AppContaRoute: typeof AppContaRoute
  AppCuradoriaRoute: typeof AppCuradoriaRoute
  AppEmpresasRoute: typeof AppEmpresasRoute
  AppFavoritosRoute: typeof AppFavoritosRoute
  AppIaraRoute: typeof AppIaraRoute
  AppImpactoRoute: typeof AppImpactoRoute
  AppLaboratorioRoute: typeof AppLaboratorioRoute
  AppLicuriRoute: typeof AppLicuriRoute
  AppLojasRoute: typeof AppLojasRoute
  AppSertaoRoute: typeof AppSertaoRoute
  AppSobreRoute: typeof AppSobreRoute
  AppVendedorRoute: typeof AppVendedorRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppLojaIdRoute: typeof AppLojaIdRoute
  AppPedidoOrderIdRoute: typeof AppPedidoOrderIdRoute
  AppProdutoSlugRoute: typeof AppProdutoSlugRoute
  AppRastreioOrderIdRoute: typeof AppRastreioOrderIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAcademiaRoute: AppAcademiaRoute,
  AppAdminRoute: AppAdminRouteWithChildren,
  AppAssistenteRoute: AppAssistenteRoute,
  AppBlogRoute: AppBlogRoute,
  AppCarrinhoRoute: AppCarrinhoRoute,
  AppCasaDoLicuriRoute: AppCasaDoLicuriRoute,
  AppCategoriasRoute: AppCategoriasRoute,
  AppCheckoutRoute: AppCheckoutRoute,
  AppClubeDoLicuriRoute: AppClubeDoLicuriRoute,
  AppContaRoute: AppContaRoute,
  AppCuradoriaRoute: AppCuradoriaRoute,
  AppEmpresasRoute: AppEmpresasRoute,
  AppFavoritosRoute: AppFavoritosRoute,
  AppIaraRoute: AppIaraRoute,
  AppImpactoRoute: AppImpactoRoute,
  AppLaboratorioRoute: AppLaboratorioRoute,
  AppLicuriRoute: AppLicuriRoute,
  AppLojasRoute: AppLojasRoute,
  AppSertaoRoute: AppSertaoRoute,
  AppSobreRoute: AppSobreRoute,
  AppVendedorRoute: AppVendedorRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppLojaIdRoute: AppLojaIdRoute,
  AppPedidoOrderIdRoute: AppPedidoOrderIdRoute,
  AppProdutoSlugRoute: AppProdutoSlugRoute,
  AppRastreioOrderIdRoute: AppRastreioOrderIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiExtractFromUrlRoute: ApiExtractFromUrlRoute,
  ApiExtractProductsRoute: ApiExtractProductsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
